In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/kaggle/input/netflix-shows/netflix_titles.csv')

In [5]:
print(df)

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [6]:
missing_value = df.isnull()

In [7]:
print(missing_value)

      show_id   type  title  director   cast  country  date_added  \
0       False  False  False     False   True    False       False
1       False  False  False      True  False    False       False
2       False  False  False     False  False     True       False
3       False  False  False      True   True     True       False
4       False  False  False      True  False    False       False
...       ...    ...    ...       ...    ...      ...         ...
8802    False  False  False     False  False    False       False
8803    False  False  False      True   True     True       False
8804    False  False  False     False  False    False       False
8805    False  False  False     False  False    False       False
8806    False  False  False     False  False    False       False

      release_year  rating  duration  listed_in  description
0            False   False     False      False        False
1            False   False     False      False        False
2            False   False     False      False        False
3            False   False     False      False        False
4            False   False     False      False        False
...            ...     ...       ...        ...          ...
8802         False   False     False      False        False
8803         False   False     False      False        False
8804         False   False     False      False        False
8805         False   False     False      False        False
8806         False   False     False      False        False

[8807 rows x 12 columns]

In [9]:
df_fillna = df.fillna(0)

In [10]:
print(df_fillna)

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water                0
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans                0
4         s5  TV Show           Kota Factory                0
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb                0
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                     0  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...              0
3                                                     0              0
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                  0              0
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [12]:
duplicate_row_drop = df.drop_duplicates()

In [16]:


df['type'] = df['type'].str.strip().str.title()


df['country'] = df['country'].fillna('Unknown').str.strip().str.title()


country_replacements = {
    'United States': 'USA',
    'United States Of America': 'USA',
    'United Kingdom': 'UK',
    'South Korea': 'South Korea',
    'Russia': 'Russian Federation',
    'Hong Kong S.A.R.': 'Hong Kong',
    'Usa': 'USA',
    'Uk': 'UK',
    'India ': 'India',  
}

df['country'] = df['country'].replace(country_replacements)


df['rating'] = df['rating'].fillna('Unrated').str.strip().str.upper()

rating_replacements = {
    'UR': 'UNRATED',
    'NR': 'UNRATED',
    'TVMA': 'TV-MA',
    'TV MA': 'TV-MA',
    'TVMA ': 'TV-MA',
    'PG13': 'PG-13',
    'PG 13': 'PG-13',
    'TVPG': 'TV-PG',
    'TV Y': 'TV-Y',
    'TVY': 'TV-Y',
    'TVG': 'TV-G'
}

df['rating'] = df['rating'].replace(rating_replacements)


df['listed_in'] = df['listed_in'].fillna('Unknown').str.strip().str.title()


df['genres'] = df['listed_in'].str.split(', ')


df['director'] = df['director'].fillna('Unknown').str.strip().str.title()
df['cast'] = df['cast'].fillna('Unknown').str.strip().str.title()


df['cast_list'] = df['cast'].str.split(', ')


print(df[['type', 'country', 'rating', 'listed_in', 'director', 'cast']].sample(5))

         type country   rating  \
4144  Tv Show   Japan    TV-MA
7834    Movie     USA  UNRATED
6560  Tv Show      UK    TV-MA
7087    Movie  Canada        R
4970    Movie     USA    TV-MA

                                           listed_in         director  \
4144            Anime Series, International Tv Shows          Unknown
7834                                   Documentaries  Morgan Spurlock
6560                    British Tv Shows, Docuseries          Unknown
7087  Dramas, International Movies, Sci-Fi & Fantasy  Patricia Rozema
4970                    Action & Adventure, Comedies   Kyle Newacheck

                                                   cast
4144  Tomori Kusunoki, Yoko Hikasa, Kazuyuki Okitsu,...
7834                                            Unknown
6560  Adrian Dunbar, Sue Perkins, Charley Boorman, R...
7087  Ellen Page, Evan Rachel Wood, Max Minghella, C...
4970  Adam Devine, Anders Holm, Blake Anderson, Utka...

In [20]:
 from datetime import datetime
 df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['date_added'] = df['date_added'].dt.strftime('%d-%m-%Y')
df['date_added'] = df['date_added'].fillna('Unknown')

In [21]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [22]:

print("Before Fixing:\n", df.dtypes)


df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce').astype('Int64')  # nullable integer


df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')


df[['duration_num', 'duration_unit']] = df['duration'].str.extract(r'(\d+)\s*(\w+)')
df['duration_num'] = pd.to_numeric(df['duration_num'], errors='coerce')


print("\nAfter Fixing:\n", df.dtypes)

Before Fixing:
 show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
genres          object
cast_list       object
dtype: object

After Fixing:
 show_id                  object
type                     object
title                    object
director                 object
cast                     object
country                  object
date_added       datetime64[ns]
release_year              Int64
rating                   object
duration                 object
listed_in                object
description              object
genres                   object
cast_list                object
duration_num            float64
duration_unit            object
dtype: object

/tmp/ipykernel_36/2251555405.py:7: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')